### ISSUE TITLE
Added unwanted lines

### ISSUE THREAD

**Issue by phifuh** [rmeneely/update-yaml#2]
The action changed the wanted text but in addtion it added new lines.
The "context = ports" and "context = volumeMounts" dont belong there

   ports:
**_Context = ports_**
    - containerPort: 8000
_**Context = volumeMounts**_
    - mountPath: /data/configdb

Full action and file below:

```
name: Update a File
on:
  workflow_dispatch:
    branches:
      - main
  push:
    paths-ignore:
      - .github/**
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: rmeneely/update-yaml@v1
        with:
          infile: wsapi_pod.yaml
          varlist: 'metadata.name=updated_from_action'

```
    
    
```
creationTimestamp: "2023-06-04T13:27:21Z"
  labels:
    app: test_app
  name: update_this
spec:
  containers:
  - env:
    - name: env
      value: dev
    - name: HOSTNAME
      value: xxx
    - name: HOME
      value: /root
    image: localhost/test_v1
    name: test_app
    ports:
  Context = ports
    - containerPort: 4000
      hostPort: 4000
    - containerPort: 26000
      hostPort: 26000
  - args:
    - mongod
    env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: test
    - name: MONGO_INITDB_ROOT_USERNAME
      value: test
    - name: HOSTNAME
      value: xxx
    image: docker.io/library/mongo:5.0.17
    name: mongoDB-podified
    volumeMounts:
  Context = volumeMounts
    - mountPath: /data/configdb
      name: xxx
    - mountPath: /data/db
      name: xxx
  volumes:
  - name: xxx
    persistentVolumeClaim:
      claimName: xxxx
  - name: xxx
    persistentVolumeClaim:
      claimName: xxx
```
